# Generated by Django 5.0.4 on 2024-05-19 21:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_profile_likes_profile_bio_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
